server:
  port: 6666

spring:
  application:
    name: gateway-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/

zuul:
  ignored-services: '*'
  routes:
    auth-server:
      path: /uaa/**
      serviceId: auth-server
      sensitiveHeaders:
      strip-prefix: false

    resource-server:
      path: /demo/**
      serviceId: resource-server
      sensitiveHeaders:
      strip-prefix: false

logging:
  config: classpath:logback.xml



