server:
  port: 8081

spring:
  application:
    name: CONSUMER-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/

logging:
  config: classpath:logback.xml




