server:
  port: 7777

spring:
  application:
    name: zuul-gateway-server
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/

zuul:
  routes:
    auth-server:
      path: /demo/**
      serviceId: PROVIDER-SERVICE
      sensitiveHeaders: '*'
logging:
  config: classpath:logback.xml



