spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/

logging:
  config: classpath:logback.xml


