server:
  port: 8080

spring:
  application:
    name: gateway-api-zuul
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data.mongodb:
    host: localhost
    port: 27017


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: aFuth/register

logging:
  config: classpath:logback.xml



